/**
 * Entity store — the single source of truth for all live moving entities
 * (aircraft, ships) currently shown on the map.
 *
 * Built with Zustand (a tiny React state library). Think of it like a live
 * spreadsheet: the WebSocket hook writes rows into it, and the map layers
 * read rows from it to decide what dots to draw.
 *
 * Data flow:
 *   WebSocket message → useEntityStream hook → store actions → map re-render
 *
 * Client-side TTL expiry:
 *   Even if the server never sends a "remove" message (AIS has no clean
 *   remove signal), entities are pruned here after 2× their source cadence:
 *     ADS-B: 30 s  (2 × 15 s poll)
 *     AIS:   20 min (2 × 10 min silence window)
 */

import { create } from 'zustand'
import type { NormalizedEntity } from '../types/entities'

/** TTL (time-to-live) in milliseconds, keyed by entity source. */
const TTL_MS: Record<string, number> = {
  adsb:      30_000,      // 30 seconds
  ais:       1_200_000,   // 20 minutes
  satellite: Infinity,    // positions are regenerated by Web Worker every 10 s
}

interface EntitiesState {
  /** All currently tracked entities, indexed by entity id for O(1) lookup. */
  entities: Map<string, NormalizedEntity>

  /**
   * Replace (or merge) the store with the initial snapshot from the server.
   * New entities are added; existing ones are overwritten only if the
   * incoming timestamp is newer (prevents snapshot from rolling back a live update).
   */
  applySnapshot: (incoming: NormalizedEntity[]) => void

  /** Apply a single live position update from the WebSocket. */
  applyUpdate: (entity: NormalizedEntity) => void

  /** Remove an entity immediately (server sent an explicit remove message). */
  removeEntity: (id: string) => void

  /**
   * Delete all entities whose last timestamp is older than their source TTL.
   * Call this on a timer (every ~5 s) to clean up stale entities when the
   * server's "remove" signal is missing (e.g. AIS).
   */
  pruneStale: () => void
}

export const useEntitiesStore = create<EntitiesState>((set, get) => ({
  entities: new Map(),

  applySnapshot: (incoming) =>
    set((state) => {
      const next = new Map(state.entities)
      for (const e of incoming) {
        const existing = next.get(e.id)
        // Only overwrite if this snapshot row is newer than what we already have.
        if (!existing || new Date(e.timestamp) >= new Date(existing.timestamp)) {
          next.set(e.id, e)
        }
      }
      return { entities: next }
    }),

  applyUpdate: (entity) =>
    set((state) => {
      const existing = state.entities.get(entity.id)
      // Discard out-of-order updates: only apply if this message is at least
      // as recent as what we already have. Redis Pub/Sub does not guarantee
      // ordering across reconnects, so stale messages can arrive occasionally.
      if (existing && new Date(entity.timestamp) < new Date(existing.timestamp)) {
        return state // no change
      }
      const next = new Map(state.entities)
      next.set(entity.id, entity)
      return { entities: next }
    }),

  removeEntity: (id) =>
    set((state) => {
      const next = new Map(state.entities)
      next.delete(id)
      return { entities: next }
    }),

  pruneStale: () => {
    const now = Date.now()
    const { entities } = get()
    const stale: string[] = []

    for (const [id, entity] of entities) {
      const ttl = TTL_MS[entity.source] ?? 30_000
      if (ttl === Infinity) continue
      if (now - new Date(entity.timestamp).getTime() > ttl) {
        stale.push(id)
      }
    }

    if (stale.length === 0) return

    set((state) => {
      const next = new Map(state.entities)
      for (const id of stale) next.delete(id)
      return { entities: next }
    })
  },
}))
